# Generated by Django 4.2 on 2025-02-18 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_user_task_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='email',
            new_name='user',
        ),
    ]
